FROM python:3.9-slim

LABEL maintainer="saihong@icsc.com.tw"

ENV FLASK_APP app.py
ENV EDITION SELF_HOSTED
ENV DEPLOY_ENV PRODUCTION

EXPOSE 5001

WORKDIR /app

RUN apt-get update && \
    apt-get install -y bash curl wget vim gcc g++ python3-dev libc-dev libffi-dev libpq-dev

COPY ./ava/requirements.txt /app/ava/requirements.txt

RUN pip install -r /app/ava/requirements.txt

COPY ava/ /app/ava
COPY config/ /app/config
COPY data/ /app/data
COPY docker/ /app/docker
COPY skills/ /app/skills

COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ARG COMMIT_SHA
ENV COMMIT_SHA ${COMMIT_SHA}

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
